---
development:
  cloud_name: cfrebooted
  api_key: '733989873497134'
  api_secret: t5ynMErsPZGKPpU79uGoE4XKfWI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: cfrebooted
  api_key: '733989873497134'
  api_secret: t5ynMErsPZGKPpU79uGoE4XKfWI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: cfrebooted
  api_key: '733989873497134'
  api_secret: t5ynMErsPZGKPpU79uGoE4XKfWI
  enhance_image_tag: true
  static_image_support: false
